[package]
name = "blog_os"
version = "0.1.0"
edition = "2018"


[dependencies]
bootloader = "=0.9.32"

lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
spin = "0.5.2"
volatile = "=0.2.6"


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

